sudo: required

services:
  - docker

language: python
python:
  - "3.5"
branches:
 only:
 - master
 - dev
 - ci

before_install:
 - docker pull danielweilandt/geek_docker
 - docker build -t geek_docker_ci -f docker/Dockerfile.ci .

script:
 - bash ./docker/run_tests.sh

after_success:
- pip install codecov; codecov;
